-- Create the tables shown in the diagram

/*
PATTERNS

Each pattern is assigned a unique, numbered identifier generated by a sequence
Its name is the exact name of the garment to be made
The sizes comply with European standards and range from 32 to 54
The commercial name may differ from the name
*/
create sequence pattern_seq
start with 1
nomaxvalue
nocycle
increment by 1;

create table patterns(
    pattern_id number primary key,
    pattern_name varchar2(255),
    sizing number(2,0),
    commercial_name varchar2(30),

    constraint size_larger check (sizing >= 32),
    constraint size_smaller check (sizing <= 54)
);

/*
FABRICS

The primary key of the table storing tailoring fabrics is text
The fabric’s natural origin is stored as a boolean (natural or artifical material)
*/

create table fabrics(
    id_tag char(10) primary key,
    name varchar2(25 char), --we use "char" because we want it to be 25 characters long, it would mean 25 bytes otherwise
    color varchar2(15 char),
    naturality number(1, 0)
);


/*
FINISHED PRODUCTS

In the finished products table, the primary key is assigned by a sequence
The tailor ID is the ID of the student who made the garment
The default value for the creation date is today's date
*/
create sequence fin_prod_seq
start with 1
increment by 1
nomaxvalue
nocycle;

create table finished_products(
    product_id number default fin_prod_seq.nextval primary key, 
    pattern_id number references patterns(pattern_id),
    fabric_id char(10) references fabrics(id_tag),
    user_id varchar2(50),
    creation_time date default sysdate
);

-- Let's insert 3 patterns and 3 fabrics into our table
insert into patterns(pattern_id, pattern_name, sizing, commercial_name)
values(pattern_seq.nextval, 'Mid-length pencil skirt with wide waist, side stitching', 36, 'Lady skirt');

insert into patterns(pattern_id, pattern_name, sizing, commercial_name)
values(pattern_seq.nextval, 'Long-sleeve, puffed, lined, scarf-necked blaser', 44, 'Flowery blaser');

insert into patterns(pattern_id, pattern_name, sizing, commercial_name)
values(pattern_seq.nextval, 'Short legged, button-closed pants', 50, 'Those pants');

commit;

select *
from patterns;

insert into fabrics(id_tag, name, color, naturality)
values('IX 5876', 'Faux leather', 'black', 0);

insert into fabrics(id_tag, name, color, naturality)
values('ISX 5876', 'Shirt material', 'White', 0);

insert into fabrics(id_tag, name, color, naturality)
values('ISNP-45', 'Jean', 'blue', 1);
commit;

select *
from fabrics;


--let's populate the finished_products table
insert into finished_products(pattern_id, fabric_id, user_id)
values(1, 'IX 5876', 
(select user 
from dual));

select *
from finished_products;


-- Let's try to query the patterns in U_UXF1FP's table
select *
from U_UXF1FP.fabrics;


-- Query our own table
select *
from U_JZT75Y.fabrics;

/*
Permissions

This allows us to follow the principle that everyone has access only to what they absolutely need

Permissions can be granted for every object

Granting/Giving permissions: GRANT (Your wish is granted)
Revoking/Taking permissions: REVOKE 

Permissions can be granted to: - a user
                       - a user group (user_group)
                       - everyone (public)
Any permission that can be granted can also be revoked
Permissions can be transferred: with grant option -> if specified this way, the user can grant their own permissions to others (while retaining them for themselves) 

What permissions can be granted:
- Select
- Insert
- Update
- Delete
- References
- Alter
- Index
- All (All of the above)
*/

-- Grant read permissions to user U_UXF1FP
grant select on fabrics to public; 

-- If they try to query now, it will work
select *
from U_UXF1FP.fabrics;

/*
The sewing workshop will now operate from a shared material warehouse
Let's modify our finished products table so that the foreign key points to U_UXF1FP's table
*/
grant select, references on fabrics to public;

alter table finished_products
drop constraint SYS_C00376184;

select *
from user_constraints;

alter table finished_products
add constraint public_warehouse_const foreign key
(fabric_id) references U_UXF1FP.fabrics;

--we have seen what we wanted to see, now let's make the table as it was before. 
alter table finished_products
drop constraint public_warehouse_const;

alter table finished_products
add constraint fbr_fk foreign key (fabric_id) references fabrics(id_tag);



-- Get insert permissions to the U_UXF1FP.FINISHED_PRODUCTS table
insert into U_UXF1FP.FINISHED_PRODUCT(pattern_id, fabric_id, user_id)
values(1, 'IX-5876', 
(select user 
from dual));


select *
from U_UXF1FP.finished_product;


-- Also viewing permission


-- Let’s sew a garment into the U_UXF1FP.FINISHED_PRODUCTS table

-- Now your insert privileges have been revoked

revoke all on finished_product from public;

-- Let’s try sewing another garment

-- Let’s try granting query privileges to the Vagnera user on the U_UXF1FP.FINISHED_PRODUCT table

-- Testing the "With grant option"
grant select on U_UXF1FP.finished_product to U_ESIQ96 with grant option;


select *
from U_UXF1FP.finished_product;

-- Let's try granting query privileges to the Vagnera user for the U_UXF1FP.FINISHED_PRODUCTS table - once again
grant select on U_UXF1FP.finished_product to Vagnera;

-- Let's grant the U_UXF1FP user read rights to our own finished products
grant select on U_JZT75Y.finished_products to U_UXF1FP;


-- Let's join our tables and query everything from them
select *
from patterns pts full outer join finished_products fp on pts.pattern_id = fp.pattern_id
full outer join fabrics fbr on fp.fabric_id = fbr.id_tag;
